export const ACTION_TYPE = {
  CLOSE_MODAL: 'CLOSE_MODAL',
  LOGOUT: 'LOGOUT',
  OPEN_MODAL: 'OPEN_MODAL',
  REMOVE_BOOKING: 'REMOVE_BOOKING',
  RESET_HOTEL: 'RESET_HOTEL',
  SET_BOOKING: 'SET_BOOKING',
  SET_HOTELS: 'SET_HOTELS',
  SET_HOTEL: 'SET_HOTEL',
  SET_USER_BOOKINGS: 'SET_USER_BOOKINGS',
  SET_USER: 'SET_USER',
};
